### ISSUE TITLE
csdm_reapi + yapb вопрос

### ISSUE THREAD

**Issue by chihuahuashka** [wopox1337/CSDM-ReAPI#1]
Прошу добавить регистрацию кваров mp_freeforall & csdm_active, для того что бы yapbot подружить с этим ксдм модом. Спасибо. https://github.com/jeefo/yapb/issues/73

**Comment by wopox1337** [comment]
Хорошо, учту пожелание

**Comment by wopox1337** [comment]
https://github.com/DevCSru/CSDM-ReAPI/issues/3 related
