### ISSUE TITLE
Latest version no spawn at join ?

### ISSUE THREAD

**Issue by UnrealKaraulov** [wopox1337/CSDM-ReAPI#54]
L 10/12/2021 - 12:04:16: World triggered "Round_Start"
L 10/12/2021 - 12:04:18: "K P A C U B O<10><STEAM_1:0:1503738329><>" entered the game
L 10/12/2021 - 12:04:18: "не ник<11><STEAM_0:1:46748090><>" entered the game
L 10/12/2021 - 12:04:19: "не ник<11><STEAM_0:1:46748090><>" joined team "TERRORIST"
@wopox1337 
Вхожу за террористов и все, пишет что я мертв и не идет воскрешение. 
Похоже на то что это появилось после обновления до последней версии CSDM_REAPI

**Comment by UnrealKaraulov** [comment]
@wopox1337 похоже "кто-то" заставляет всех без исключения входить в наблюдатели))) удалил одну строку кода и все заработало, можешь исправить?

**Comment by wopox1337** [comment]
related https://github.com/wopox1337/CSDM-ReAPI/issues/56

**Comment by UnrealKaraulov** [comment]
@wopox1337 я считаю так, с быстрым входом выбор команд в твоём плагине не успевает сработать в итоге все в наблюдении. Можешь исключение добавить для квара быстрого входа.
