### ISSUE TITLE
`csdm_misc`: It does not allow you to choose a team

### ISSUE THREAD

**Issue by stambeto2006** [wopox1337/CSDM-ReAPI#56]
@wopox1337 The latest version when I released this plugin (csdm_misc.amxx) and does not allow me to select teams to enter when I stop it is no problem!

**Comment by wopox1337** [comment]
Thank you. What settings were used?

**Comment by UnrealKaraulov** [comment]
> Thank you. What settings were used?

https://github.com/wopox1337/CSDM-ReAPI/blob/721588c505860e3ae3ffd77c4d6ce37bbe56ecb9/cstrike/addons/amxmodx/scripting/CSDM_ReAPI/csdm_misc.sma#L146

This code cause problem **IF TEAM != SPECTATOR JOIN SPECTATOR,** NICE LOGIC. I just remove this code and now no problem.

**Comment by UnrealKaraulov** [comment]
> Thank you. What settings were used?

@wopox1337 я забыл написать, активирован быстрый вход в игру в ReGameDLL, по этому всех кидало за спектров и они не могли играть.

**Comment by stambeto2006** [comment]
@wopox1337 Will there be a solution to this problem, as to fix some of the major bugs that came out in the latest version?

**Comment by stambeto2006** [comment]
@etojuice @wopox1337 Are there any hopes of fixing the bugs in fashion or is it no longer supported?

**Comment by etojuice** [comment]
> @etojuice @wopox1337 Are there any hopes of fixing the bugs in fashion or is it no longer supported?

which version was the last before the bug was introduced? which file is affected?

**Comment by stambeto2006** [comment]
@etojuice CSDM-ReAPI-v1.0.4 **csdm_misc.amxx** don't have problems, but next versions have problems with choose teams?

**Comment by UnrealKaraulov** [comment]
Я же написал как исправить это
