### ISSUE TITLE
Players from the same team can be killed

### ISSUE THREAD

**Issue by stambeto2006** [wopox1337/CSDM-ReAPI#60]
I tested CSDM-ReAPI with bots and real players at the same time and found a bug that players can be killed by being in the same team!

**Comment by wopox1337** [comment]
More information is needed. It is not clear why this behavior was not expected, while CSDM-ReAPI has at the moment (v1.0.5) FFA only mode.

**Comment by wopox1337** [comment]
Please provide more information. What exactly were you expecting and on what settings CSDM-ReAPI & ReGameDLL.

**Comment by stambeto2006** [comment]
I fixed this problem by doing the following: free_for_all = 0
