### ISSUE TITLE
Spawn menu : нельзя выйти из меню. И нет возможности переключаться между спавн точками

### ISSUE THREAD

**Issue by UnrealKaraulov** [wopox1337/CSDM-ReAPI#63]
Spawn menu : нельзя выйти из меню

**Comment by UnrealKaraulov** [comment]
Спавн точки сохраняются даже без нажатия "сохранить."

**Comment by UnrealKaraulov** [comment]
И нет возможности переключаться между спавн точками (если несколько штук установил неправильно и хочешь их быстро удалить)

**Comment by UnrealKaraulov** [comment]
Еще спавны не загружаются из файла когда вводишь команду. (Хотелось бы быстрая подмена спавнов, закинул файл, вписал команду, без смены карты)

Так же ошибка записи в файл, пишет 

```
// File generated by "CSDM Spawn Manager" Version: %VERSION%
// Total spawns: 1
```

Я так понял там где %VERSION% должна быть какая-то версия?

**Comment by wopox1337** [comment]
> Спавн точки сохраняются даже без нажатия "сохранить."

This is a feature, not a bug.

> там где %VERSION% должна быть какая-то версия?

You MUST use the [release version](https://github.com/wopox1337/CSDM-ReAPI/releases). In all other cases, stable and correct functioning is not guaranteed. 


closed: duplicate of https://github.com/wopox1337/CSDM-ReAPI/issues/64
