### ISSUE TITLE
AutoSpawns

### ISSUE THREAD

**Issue by UnrealKaraulov** [wopox1337/CSDM-ReAPI#65]
Доброго времени суток CSDM разработчик! Можешь добавить генератор спавнов в новую версию Spawn Manager ?

Это проще чем кажется. Вот пример.

1. Если нет CSDM спавн точек на карте, использовать стандартные и включить режим обучения.
2. Режим обучения: Отключить FFA, использовать стандартные спавны для каждой команды.
3. Каждые 30 секунд произвести следующие действия с каждым игроком.
      1. Получить координаты игрока, если игрок находится на земле (флаг ON_GROUND к примеру) 
      2. Сравнить координаты с существующими спавн точками
      3. Если дистанция больше 500 (к примеру) добавить координаты игрока в список спавн точек.
      4. Повторять пока все стандартные спавн точки не будут заменены "псевдорандомными".

Это проверено и работает идеально)) 
Потом главное что бы через спавн меню можно было бы их подкорректировать (изменить угол поворота или переместить)

**Comment by wopox1337** [comment]
> Disable FFA
At the moment (v1.0.5) other modes are not supported (not FFA). 

Thanks for the ideas, in the future it is planned to add the functionality of automatic spawn placement.
