### ISSUE TITLE
Раунд завершается при FreeForAll если не настроить в regamedll

### ISSUE THREAD

**Issue by UnrealKaraulov** [wopox1337/CSDM-ReAPI#75]
Раунд завершается при FreeForAll если убить всех врагов.

И завершается по времени например каждые 5 минут

Мод не полноценный и требует каких-то настроек в ReGameDLL!

НАДА исправить это!

**Comment by etojuice** [comment]
Вместо того чтобы подставлять в заголовок issue оскорбления, мог бы создать pull request. По сложности сравнимо с подкидыванием дров в топку. У тебя получится!
